### ISSUE TITLE
wrong precedence parsing the length operation (#)

### ISSUE THREAD

**Issue by tony-song** [boolangery/py-lua-parser#41] opened 2023-04-03 08:18 UTC
`
#tab+1
` 
is parsed to
`
LengthOp(AddOp(tab,1))
`

It should be
`
AddOp(LengthOp(tab), 1)
`

**Comment by fabi321** [comment] 2023-05-06 22:46
as far as I can tell, this is a duplicate of #38

**Comment by boolangery** [comment] 2024-10-27 10:50
Fixed on master, will release a version soon

**Closed by boolangery** 2024-10-27 10:50 UTC
